### ISSUE TITLE
i just wanted to know how to use it 

### ISSUE THREAD

**Issue by Rxbzey** [dadrum/niimbot_flutter_plugin#1]

**Comment by dadrum** [comment]
> _No description provided._

Currently, only the Android platform is supported. But you need to keep in mind that those native libraries that are used do not work very correctly. For example, I was unable to print a QR code (some kind of the same example is printed all the time) - I printed it manually using primitives.

These documents were used for implementation
Android端SDK 接口V3.1.8在线文档：
https://whjc.yuque.com/nthong/manual/qkykycd814ko97qe?singleDoc# 

Android 打印机蓝牙相关注意事项：
https://whjc.yuque.com/nthong/manual/dy0drcbsfqkm6iou?singleDoc# 

基于精臣PC端云打印快速排版：
https://whjc.yuque.com/nthong/manual/eqwn7acvk1g0ridk?singleDoc# 

精臣打印机SDK-内容排版在线文档：
https://whjc.yuque.com/nthong/manual/cq0gsb401eoc0nbh?singleDoc#

The principle is simple
1) are you searching for a printer
2) connect to the printer and get an instance of Niimbot
3) subscribe to the message streams from the printer
4) using the object from point 3, send commands to the printer

this is a simplified version of the label printing
`

class GsSticker22x14 implements IGsSticker {
  @override
  int get id => 1;

  // размер этикетки
  @override
  String get size => '22x14';

  late Niimbot _api;
  late int _count;

  final List<String> _jsonList = [];
  final List<String> _infoList = [];

  @override
  Future<void> onBufferFree(int pageIndex, int bufferSize) async {
    if (pageIndex > _count) {
      return;
    }
    await Future<void>.delayed(const Duration(milliseconds: 150));
    await _api.commitData(printDataList: _jsonList, printerInfoList: _infoList);
  }

  /// количество напечатанных страниц
  /// количество напечатанных копий текущей страницы
  @override
  Future<void> onProgress(int pageIndex, int quantityIndex) async {
    if (pageIndex == 1 && quantityIndex == _count) {
      try {
        await _api.endJob();
      } on Object {
        // print('Ошибка при завершении печати');
      }
    }
  }

  @override
  Future<void> printSticker(
      Niimbot api, String model, String number, String mac,
      [int count = 1]) async {
    _count = count;
    _api = api;
    _jsonList.clear();
    _infoList.clear();

    const double width = 22;
    const double height = 14;
    const int orientation = 90;

    const printMultiple = 8.0;
    final quantity = count;

    await api.cancelJob();
    await Future<void>.delayed(const Duration(milliseconds: 300));

    await api.drawEmptyLabel(
        width: width, height: height, rotate: orientation, fontDir: '');

    await api.drawLabelText(
        x: 10.5,
        y: 1.9,
        width: 12,
        height: 3,
        value: 'HELLO WORLD',
        fontFamily: '',
        fontSize: 2,
        rotate: 0,
        textAlignHorizontal: 0,
        textAlignVertical: 0,
        lineModel: 4,
        letterSpace: 0,
        lineSpace: 0,
        mFontStyles: [true, false, false, false]);


    final jsonByte = await api.generateLabelJson();
    final jsonStr = String.fromCharCodes(jsonByte);

    _jsonList.add(jsonStr);
    //
    final jsonInfo = '{  '
            '\"printerImageProcessingInfo\": '
            '{    '
            '\"orientation\":' +
        orientation.toString() +
        ',' +
        '   \"margin\": [      0,      0,      0,      0    ], ' +
        '   \"printQuantity\": ' +
        quantity.toString() +
        ',  ' +
        '  \"horizontalOffset\": 0,  ' +
        '  \"verticalOffset\": 0,  ' +
        '  \"width\":' +
        width.toString() +
        ',' +
        '   \"height\":' +
        height.toString() +
        ',' +
        '\"printMultiple\":' +
        printMultiple.toString() +
        ',' +
        '  \"epc\": \"\"  }}';
    _infoList.add(jsonInfo);

    await Future<void>.delayed(const Duration(milliseconds: 300));

    await api.setTotalQuantityOfPrints(1);
    await api.startPrintJob(density: 3, paperType: 1, printMode: 1);
    await api.commitData(printDataList: _jsonList, printerInfoList: _infoList);
  }

}
`
